version: "3.8"
services:

  registry: 
    container_name: docker_registry   
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/test.ir/test.ir.cer
      REGISTRY_HTTP_TLS_KEY: /certs/test.ir/test.ir.key
      # REGISTRY_AUTH: htpasswd
      # REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      # REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    restart: always
    volumes:
      - ./data:/var/lib/registry
      - ./certs:/certs
      - ./auth:/auth
      #- ./config.yml:/etc/docker/registry/config.yml
